### ISSUE TITLE
Use "official" faster-whisper models

### ISSUE THREAD

**Issue by guillaumekln** [jordimas/whisper-ctranslate2#21]
Hi,

Would it be possible for this project to use the same models that are downloaded by faster-whisper? See the available models here: https://huggingface.co/guillaumekln

Using the same models would ensure consistency between this project and faster-whisper. For example your models do not seem to contain a recent fix to the configuration:

https://huggingface.co/guillaumekln/faster-whisper-tiny.en/commit/7d45cf02c1ed72d240c0dbf99d544d19bef1b5a3
https://huggingface.co/guillaumekln/faster-whisper-tiny/commit/518d6e0b5a068b278f66842b17377f9523de5cd1

(all models were updated similarly)

**Comment by jordimas** [comment]
Hello

Yes, this makes sense. I built by own model download system before faster-whisper was providing the functionality.

The only thing that I need to be able to do it right now is a new faster-whisper version that includes this change:
https://github.com/guillaumekln/faster-whisper/commit/2b53dee6b697ba1364d7ba1b1c1ce3a6a2dc05df, since users in whisper-ctranslate2 can specify the directory what they want to use as cache. If you can do a new faster-whisper release it will be great, thanks

**Comment by guillaumekln** [comment]
I just released a new version 0.5.0.

**Comment by jordimas** [comment]
We use now the official models. Thanks for your support improving model loading in faster-whisper
