### ISSUE TITLE
How to turn off --highlight_words ?

### ISSUE THREAD

**Issue by zx3777** [jordimas/whisper-ctranslate2#28]
When i use --word_timestamps True , the highlight word will auto turn on，and when i add --highlight_words False ，it show error：whisper-ctranslate2: error: unrecognized arguments: --highlight_words False.

123 is example. the result srt like this: 

These three lines are the same subtitle
![1 (2)](https://user-images.githubusercontent.com/35957748/233910228-aee7c9c2-35d8-4a64-a1f0-c0a7838bf825.jpg)

**Comment by jordimas** [comment]
Hello,

Two comments:

1) This is the expected behaviour as provided by [Faster-whisper](https://github.com/guillaumekln/faster-whisper). The option _word_timestamps_ provides timing at word level.  The <u>WORD</u> is added by Faster-whisper for you to identify which word is the word stamp specified.

00:00:01,360 --> 00:00:01,800
Amb matèria de finançament<u> públic</u> universitària, crec, sincerament,

00:00:01,800 --> 00:00:02,700
Amb matèria de finançament públic<u> universitària,</u> crec, sincerament

2) whisper-ctranslate2 does not have a _highlight_word_ option, it's normal that gives you an error.

Hopefully this makes sense. Thanks

**Comment by zx3777** [comment]
So this can't be closed？

There's also a bug: when recognizing long videos, often get stuck, sometimes a large chunk of dialogue is skipped, sometimes 20 or 30 minutes of dialogue is skipped.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jordimas** [comment]
Regarding the problem with "long videos". Can you open another issue please? 

I need:
* Operating system that you use
* Whisper-ctranslate2 version
* Using CPU/GPU
* Share a file that helps me to reproduce the problem

**Comment by zx3777** [comment]
But I use the original whisper, it will not add u characters.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jordimas** [comment]
Thanks for your feedback

In the last version I added the option   --highlight_words  as the original Whisper and it's off by default as in OpenAI Whisper. It should behave the same now
